# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties - Minecraft 26.2
# Check https://fabricmc.net/develop for the latest exact versions
minecraft_version=26.2
yarn_mappings=26.2+build.1
loader_version=0.16.14

# Mod Properties
mod_version=1.1.0
maven_group=com.rvmplestiltskin
archives_base_name=the-dark-one

# Dependencies
fabric_version=0.119.0+26.2
